name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build and check size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Install deps
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Check bundle size
        run: yarn size

      - name: Check website
        run: yarn workspace @chonky2/website check

      - name: Build website
        run: yarn workspace @chonky2/website build
